[package]
name = "fall-test"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
lazy_static = "0.2"
fall_tree = { path = "../fall_tree" }
fall_parse = { path = "../fall_parse" }
